# Assignment 10

After the training, the parameters (weights and bias) of the neural network instance should be printed and the error curve over the epochs should be plotted in logarithmic scale. Furthermore, the target data and the data as outputted by the final neural network is shown in a scatter plot. Since the input data is generated randomly, you may expect different plots for every execution of the notebook. The whole function is called twice, one time for each dataset. 

In [2]:
import numpy as np
np.set_printoptions(threshold=10) # printing setup
import matplotlib.pyplot as plt

In [3]:
# This formula shall be imitated by the neural network
def formula_1(x):
    return x + 0.75

# This formula shall be imitated by the neural network, too
def formula_2(x):
    return(np.sin(x) + 0.5)

In [4]:
# Input data
X = np.random.uniform(low=-0.5, high=1.55, size=100)# make 100 uniformly distributed samples
X = X.reshape(-1, 1) # -1 indicates "as many rows as required"
print(X) # input data as column vector

[[ 0.83618953]
 [ 1.43673868]
 [ 0.93389609]
 ...
 [-0.36146105]
 [ 0.49385768]
 [-0.15143711]]


In [5]:
# Target values with formula_1
y_1 = np.array([formula_1(x) for x in X.flatten()]) # one output per sample, |X|-many samples
y_1 = y_1.reshape(-1, 1)
y_1 # target data as column vector

array([[1.58618953],
       [2.18673868],
       [1.68389609],
       ...,
       [0.38853895],
       [1.24385768],
       [0.59856289]])

In [6]:
# Target values with formula_2
y_2 = np.array([formula_2(x) for x in X.flatten()]) # one output per sample, |X|-many samples
y_2 = y_2.reshape(-1, 1)
y_2 # target data as column vector

array([[1.24209437],
       [1.49102772],
       [1.30394307],
       ...,
       [0.14635875],
       [0.97402613],
       [0.34914105]])

### Code below contains the parts to be edited

In [7]:
# Simple neural-network based regressor
class NeuralNetwork:
    
    # Function called at object initialization
    def __init__(self):
        
        # These are members of the class. You can access them in every method by "self.var_name" and from outside the class with "instance_name.var_name"
        
        # Sample to compute pass with
        self.X          = 0.0 # set me!
        self.y          = 0.0 # set me!
        
        # Parameters to be learned
        self.weight_1   = 1.0 #np.random.uniform(low=-0.01, high=0.80, size=100) # teach me!
        self.weight_2   = 1.0 #np.random.uniform(low=-0.02, high=0.90, size=100) # teach me!
        self.bias       = 1.0 # teach me!
        
        # State information
        self.hidden     = 0.0 # use me!
        self.output     = 0.0 # use me!
        self.error      = 0.0 # use me!
        
    # Set sample to be used in feed-forward and back-propagation pass
    def set_sample(self, X, y):
        self.X = float(X)
        self.y = float(y)
        
    # (a) Feed-forward pass
    def feed_forward(self):
        self.hidden= self.X* self.weight_1 + self.bias
        self.hidden= 1/(1+np.exp(-self.hidden))
        self.output= self.hidden* self.weight_2
        return 0.5* np.square(self.output- self.y)
        
        # TODO: Feed-forward pass and error estimation, store results in state information members
        # Consider the loss function: 0.5 ∗ (𝑡𝑎𝑟𝑔𝑒𝑡 − 𝑜𝑢𝑡𝑝𝑢𝑡)2

      
    # (b) Back-propagation pass
    def back_prop(self):
        
        # TODO: Derivations of parameters
        # TODO: Update the parameters with learning rate of 0.01
        
def execute_nn(X, y):
    
    # Instantiate neural network
    nn = NeuralNetwork()
    
    # Collect mean error of each epoch to plot it later
    epoch_error = []

    # Perform multiple epochs, aka inputting the dataset multiple times
    for epoch in range(0,100):
        error=[]
        for i in range(0, len(X)):
            nn.set_sample(X[i], y[i])
            error.append(nn.feed_forward())
            nn.back_prop()
        epoch_error.append(np.mean(error))

        
        # Example use of neural network class
        # nn = NeuralNetwork() # instantiates neural network
        # nn.set_sample(2,5) # sets sample with 2 as input and 5 as target
        # nn.feed_forward() # perform feed-forward to calculate output
        # nn.back_prop() # use difference between target and actual output to update parameters
        #Remember final error of each epoch in "epoch_error"
        print("TODO (c)") # remove this line, just here to produce no compile error in initial setup
        
    # Print final parameters of trained neural network
    print("Weight_1:"+ str(nn.weight_1))
    print("Weight_2:" + str(nn.weight_2))
    print("Bias:" + str(nn.bias))
    
    # Plot epoch errors with logarithmic transformation
    plt.plot(list(range(len(epoch_error))), np.log(epoch_error))
    ax = plt.gca()
    ax.set_xlabel('# Epoch')
    ax.set_ylabel('Error')
    plt.show()
    
    # Plot datapoints as originally transformed and as transformed by neural network
    computed = []
    for i in range(0, X.shape[0]):
        nn.set_sample(X[i], y[i])
        nn.feed_forward()
        computed.append(nn.output)
    plt.scatter(X.transpose().flatten(), y.transpose().flatten(), c='blue', s=16)
    plt.scatter(X.transpose().flatten(), computed, c='red', s=16)
    plt.show()

print("Imitation of formula 'x+0.75'")
execute_nn(X,y_1)
print()
print("Imitation of formula 'sin(x)+0.5'")
execute_nn(X,y_2)

IndentationError: expected an indented block (<ipython-input-7-a477fbfda57f>, line 45)